### ISSUE TITLE
Idle Status

### ISSUE THREAD

**Issue by matko93** [brewpi-remix/brewpi-script-rmx#101]
I can't get the script to work. The status remains in "Idle" even after 4 hours.
I have attached arduino relays and these work. 
I also try to set the "Assigned to" just don't want to save on "Beer 1". 
I 
![11](https://user-images.githubusercontent.com/19798420/71554866-228c5480-2a25-11ea-8bc1-6a1dcc5b3d14.PNG)
![12](https://user-images.githubusercontent.com/19798420/71554867-228c5480-2a25-11ea-8ffa-2f928ad0dc46.PNG)
![13](https://user-images.githubusercontent.com/19798420/71554868-228c5480-2a25-11ea-93e4-cab77f8c2062.PNG)

**Comment by lbussy** [comment]
It looks like you have your system set to “Beer Constant” but only have one temp sensor configured.   You need two for that.  If you only have one, use “Chamber Constant.”

Also, please see the documentation [here](https://brewpi-userdocs-rmx.readthedocs.io/en/latest/devices/index.html) for instructions on how to set up devices correctly.

**Comment by lbussy** [comment]
I've not heard back from you on this.  If I don't hear back I'll assume you have it fixed and go ahead an close it.
