### ISSUE TITLE
BlueBean Tilt Battery Readout

### ISSUE THREAD

**Issue by lbussy** [brewpi-remix/brewpi-script-rmx#142]
Think about how we can show a BlueBean-type battery indicator.

**Comment by thorrak** [comment]
You're thinking only for the Gen 1 tilts, or are you thinking of doing something where you assume the number of weeks on a battery and use that to come up with a %?

**Comment by lbussy** [comment]
Was exchanging email with a user who has a BlueBean and I pretty much wrote those off (after I sent yours back.)  I thought I might be able to add a conditional display between the new or old.

**Comment by thorrak** [comment]
If you want to borrow it again, just let me know. (Preferably in the next week)

**Comment by lbussy** [comment]
That would be cool - otherwise, I'm going to write stuff and ask you to test.  :)

**Comment by lbussy** [comment]
This is still kicking my ass.  `gattool` has been removed now, and there's no way (yet) to use any of the current Python libs to get this information.

**Comment by lbussy** [comment]
Not going to fix this.  Support has been sketchy and there's just not enough of these users.
