### ISSUE TITLE
Install:  Error installing numpy

### ISSUE THREAD

**Issue by lbussy** [brewpi-remix/brewpi-script-rmx#192]
New to Bullseye apparently; the installation on a new system fails on numpy.

**Comment by lbussy** [comment]
The version of numpy frozen in requirements.txt is 1.16.2.  Bullseye brings in Python 3.9.x which apparently changes enough to break installing numpy.  If I use the compatible release clause, numpy installs correctly.

**Comment by thorrak** [comment]
What is Bullseye?

**Comment by lbussy** [comment]
> What is Bullseye?

The new version of Debian.  Raspbian wrapped it in on their release on October 30th.
